server:
  port: 5000
  compression:
    enabled: true
    min-response-size: 1024
  shutdown: graceful
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  batch:
    initialize-schema: always
  jackson:
    serialization:
      fail-on-empty-beans: false
  flyway:
    baseline-on-migrate: true

product:
  image: C:\Users\szela\Desktop\java\store-images

---
server:
  port: 8080
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/store?useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw&autoReconnect=true&characterEncoding=UTF-8&useUnicode=yesjdbc:mysql://localhost:3306/serwis?useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw&autoReconnect=true&characterEncoding=UTF-8&useUnicode=yes
    username: root
    password: password