spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store?useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw&autoReconnect=true&characterEncoding=UTF-8&useUnicode=yesjdbc:mysql://localhost:3306/serwis?useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw&autoReconnect=true&characterEncoding=UTF-8&useUnicode=yes
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  batch:
    initialize-schema: always

