pipeline {
    agent any
    tools {
        jdk 'JDK'
    }
    stages {
        stage('test') {
            steps {
                bat """
                cd store
                mvn clean test"""
            }
        }
       stage('package') {
            steps {
                bat """
                cd store
                mvn package -DskipTests"""
            }
       }
    }
}