pipeline {
    agent any
    tools {
        jdk 'JDK'
    }
    stages {
        stage('build') {
            steps {
                bat """
                cd store
                mvn clean test"""
            }
        }
    }
}